### ISSUE TITLE
[Feature] Ausnahme-Regel

### ISSUE THREAD

**Issue by akroii** [fritzmg/contao-inherit-article#1]
Ein Artikel vererbt nach unten dessen Elemente bei aktivierter Vererbung.
Es wäre toll wenn man eine Ausnahme setzen könnte.

Wie hier:

```
-- Artikel (Vererbte Elemente)
--- Artikel 2
--- Artikel 3
---- Artikel 3.1 (Ausnahme, Vererbe ab hier neue Elemente)
---- Artikel 3.2
---- Artikel 3.3
```

**Comment by fritzmg** [comment]
Hm, angedacht hätte ich, dass man bspw. das maximale Level an Vererbung angeben könnte. Also in deinem ersten Artikel würdest du dann als "Stop-Level" (ähnlich wie im Navigationsmodul also) die Zahl `1` eingeben, das würde bedeuten, dass der Artikel maximal ein Level nach unten vererbt wird. In deinem Beispiel also nur auf die Seiten wo sich auch Artikel 2 und 3 befinden. Auf der Seite wo sich Artikel 3.1, 3.2 und 3.3 befinden würde der Artikel dann nicht mehr aufscheinen.

Oder möchtest du tatsächlich nur spezifische Ausnahmen festlegen können? Also dass man im Artikel eine oder mehrere Seiten angeben kann, die von der  Vererbung ausgeschlossen sein sollen.

Derartige Features übersteigen vielleicht das Prinzip der Extension - hier bietet eigentlich zB die Extension [psi-4ward/boxes4ward](https://github.com/psi-4ward/boxes4ward) umfangreiche Möglichkeiten :)

**Comment by akroii** [comment]
Vom Prinzip "nach unten hin vererben" würde es ja logisch sein, soweit zu ererben, bis es von einer anderen Regel unterbrochen wird..

Ist boxes4ward für Contao 3.4.4 noch aktuell?

**Comment by fritzmg** [comment]
> Vom Prinzip "nach unten hin vererben" würde es ja logisch sein, soweit zu ererben, bis es von einer anderen Regel unterbrochen wird..

Ok, ja dann würde ich es eben mit einem "Stop-Level" wie bei der Navigation implementieren.

> Ist boxes4ward für Contao 3.4.4 noch aktuell?

Ich denke schon. Die Version im ER2 wird nicht mehr aktualisiert. Aber auf GitHub wurde in Version 2.0.5 bspw. extra die composer.json geändert, damit es in Contao 3.1 bis unter Contao 4 installiert werden kann. Unter Contao 3.4 bzw. 3.5 habe ich boxes4ward jedoch noch nicht getestet.

**Comment by fritzmg** [comment]
Implemented in 432bf5f08b5af5ab3995382409affb221a99d7bb

**Comment by akroii** [comment]
goil :+1:
