### ISSUE TITLE
Fehler in Kombination mit isotope Produktleser

### ISSUE THREAD

**Issue by pet21221** [fritzmg/contao-inherit-article#10]
Nach Installation der "contao-inherit-article"-Extension in Kombination mit isotope ab 2.6 funktioniert der Produktleser bei isotope nicht mehr korrekt. Das Produkt / der Produktleser wird nicht korrekt dargestellt. Stattdessen wird teilweise weiterhin die Produktliste angezeigt. Im Seitentitle erscheint der Title der 404-Fehlerseite.

Alle Vererbungen sind deaktiviert, bspw. eine Vererbung wurde nicht gesetzt. Das Problem taucht direkt nach Installation der "contao-inherit-article"-Extension auf.

**Comment by fritzmg** [comment]
Fixed in version `3.0.0` :)
