### ISSUE TITLE
Fehler nach Update auf Contao 4.9.24

### ISSUE THREAD

**Issue by webworker-ecco** [fritzmg/contao-inherit-article#11]
Nach Update auf Contao 4.9.24 wird da FE nur mehr als weiße Seite ausgegeben. 
Backend funktioniert weiterhin problemlos.

Es sind zahlreiche Erweiterungen installiert, die folgenden Meldungen lassen mich den Fehler allerdings hier verorten.

Ein herabsetzen auf die 4.9.23 behebt den Fehler.

Im Debug Mode gibt es den folgenden Fehler:
`Uncaught PHP Exception ErrorException: "Warning:  Creating default object from empty value" at  C:\laragon\www\dormagendebug\vendor\fritzmg\contao-inherit-article\src\EventListener\InheritArticleListener.php  line 129                                {     "exception": {} }`

Der Stack Trace sagt:
`ErrorException:
Warning: Creating default object from empty value

  at XXX\vendor\fritzmg\contao-inherit-article\src\EventListener\InheritArticleListener.php:129
  at InheritArticleBundle\EventListener\InheritArticleListener->onGeneratePage(object(PageModel), object(LayoutModel), object(PageRegular))
     (XXX\vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:191)
  at Contao\PageRegular->prepare(object(PageModel))
     (XXX\vendor\contao\core-bundle\src\Resources\contao\pages\PageRegular.php:48)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (XXX\vendor\contao\core-bundle\src\Resources\contao\controllers\FrontendIndex.php:337)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (XXX\vendor\symfony\http-kernel\HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (XXX\vendor\symfony\http-kernel\HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (XXX\vendor\symfony\http-kernel\Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (XXX\web\index.php:31)`

**Comment by fritzmg** [comment]
I am assuming this is under PHP 8?

**Comment by webworker-ecco** [comment]
PHP 7.4.3

**Comment by Webstylerin** [comment]
Same problem here after upate to Contao 4.9.24.

PHP Version 7.4.26

![2022-01-10 09-47-57](https://user-images.githubusercontent.com/3033160/148738828-c7878ae4-33e4-40d7-b59d-95747d4f43b7.png)
.

**Comment by fritzmg** [comment]
Unfortunately I am unable to reproduce the issue.

**Comment by webworker-ecco** [comment]
I have not yet been able to reproduce the problem in a fresh Contao installation.
The best I can offer is access to a copy of the page.
Here then is the list of installed extensions.

@Webstylerin Maybe there is an intersection. Uninstalling extensions one by one did not help to solve the problem.

```{
   "type": "project",
   "require": {
      "alnv/catalog-manager": "^1.31",
      "alnv/catalog-manager-export": "^1.2",
      "christianbarkowsky/contao-tiny-compress-images": "^1.0",
      "clickpress/contao-clickpress-grid": "^1.2",
      "codefog/contao-mobile_menu": "^2.7",
      "contao/calendar-bundle": "4.9.23",
      "contao/conflicts": "*@dev",
      "contao/faq-bundle": "4.9.23",
      "contao/listing-bundle": "4.9.23",
      "contao/manager-bundle": "4.9.23",
      "contao/news-bundle": "4.9.23",
      "contao/tcpdf-bundle": "^1.2",
      "derhaeuptling/contao-mega-menu": "^1.0",
      "do-while/contao-backupdb-bundle": "^1.4",
      "do-while/contao-pdf-template-bundle": "^1.3",
      "erdmannfreunde/euf_overlay": "^1.3",
      "fipps/contao-rssimport-bundle": "^4.1",
      "fritzmg/contao-file-access": "^2.2",
      "fritzmg/contao-inherit-article": "^2.1",
      "fritzmg/contao-swiper": "^3.4",
      "hofff/contao-calendarfield": "^4.0",
      "madeyourday/contao-rocksolid-custom-elements": "^2.2",
      "mediamotionag/contao-backend-optim-bundle": "^1.0",
      "numero2/contao-panorama-ce": "^1.0",
      "oveleon/contao-component-style-manager": "^2.4",
      "oveleon/contao-cookiebar": "^1.7",
      "terminal42/contao-leads": "^1.4",
      "terminal42/notification_center": "^1.5",
      "w3scout/contao-searchfaq-bundle": "^1.0"
   },
   "extra": {
      "contao-component-dir": "assets"
   },
   "scripts": {
      "post-install-cmd": [
         "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
      ],
      "post-update-cmd": [
         "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
      ]
   }
}```

**Comment by fritzmg** [comment]
Please post the complete `composer.json` (with three back ticks).

**Comment by webworker-ecco** [comment]
Have updated my post

**Comment by fritzmg** [comment]
This is an error within Contao 4.9.24: https://github.com/contao/contao/issues/3894

**Comment by fritzmg** [comment]
Btw. this issue occurs because you are using an outdated version of this extension. The newest version is `3.0.1`. Your `composer.json` requires only `^2.1`.

**Comment by webworker-ecco** [comment]
Ah, ok. Thank you for your efforts. Then we'll wait for the next update.

**Comment by fritzmg** [comment]
> Then we'll wait for the next update.

Just update the extension to `^3.0` ;)
