### ISSUE TITLE
Artikel priorisieren

### ISSUE THREAD

**Issue by pet21221** [fritzmg/contao-inherit-article#2]
Hallo,

es wäre sehr toll, wenn man die Artikel priorisieren kann. Damit die vererbten Artikel auch mal nicht als erstes kommen. 

Ich nutze "inherit_article" für das Submenü auf der Linken Seite. Jede Main Seite hat ein eigenes Menü, das wiederum auf den entsprechenden Unterseiten jeweils angezeigt wird. Nun kann es aber vorkommen, dass ich auf einer Unterseite einen Vermerk (Neues Artikel) über das Linke Menü hinzufügen möchte. Sobald ich dies mache, erscheint es immer unter dem Menü. Ich möchte es aber über dem vererbten Artikel anzeigen.  

Gruß

**Comment by fritzmg** [comment]
Implemented in a688b3513404034b3618d68cdf154319cf4b7df8

**Comment by fritzmg** [comment]
available in release `1.2.0`

**Comment by pet21221** [comment]
Vielen Dank; dass finde ich sehr gut. Doch was passiert im Falle eines, wenn ich vor und nach dem vererbten Artikel jeweils einen Artikel einblenden möchte? Dieses Szenario kann öfters vorkommen. Gerade wenn man den vererbten Artikel in einer der ersten Seiten erstellt und dieses von vielen Unterseiten übernommen wird. 

Macht es nicht mehr Sinn, wenn man die Möglichkeit hat, die Artikel auch nach einem Int sortiere? Sprich ich gebe dem vererbten Artikel einen Int von 2. Auf einer Unterseite platziere ich zwei Artikel auf die selbe Spalte jeweils mit einem Int Wert von 1 und 3. Man könnte es dann nach diesem Int sortieren. Sprich 1, 2 und 3. So kenne ich das von einem anderen CMS.

Ich weiß nicht inwiefern Contao es anbietet, dies zu ermöglichen. Ich kenne das aus einem anderen CMS und fand diese Lösung schon immer sehr gut.

**Comment by fritzmg** [comment]
Achso, hm. Naja so ein Input Field bereitstellen ist nicht schwierig. Es ginge eher darum, wie diese Priorisierung am besten umgesetzt werden könnte.

Ich würde aber sagen, dass für solche erweiterten Anwendungsfälle [psi-4ward/boxes4ward](https://github.com/psi-4ward/boxes4ward) doch besser geeignet ist.

**Comment by pet21221** [comment]
Evtl. in der Artikel Tabelle eine neue Spalte mit prio anlegen. Standardgemäß ist es die 0. Auf der Artikel bearbeiten Seite kann man bei Bedarf die Prio von 0 auf irgendeinen anderen Wert setzen. 

Beim Laden der Artikel wird an erster Stelle ein Order auf Prio gemacht.

Alles andere bleibt, wie es ist.

Ist dies nicht mit Contao möglich?

**Comment by fritzmg** [comment]
Eine weitere Spalte für die Priorität anlegen ist nicht das Problem. Das Problem ist den Algorithmus dafür zu schreiben. Die Artikel zuerst nach dieser Spalte über die Datenbankabfrage mit `ORDER BY` sortieren zu lassen ist nicht möglich (unabhängig von Contao), da diese Artikel sich ja auf anderen Seiten befinden und man daher den Seitenbaum traversieren muss. Die entsprechende Sortierung muss dann in PHP erfolgen. Sieh' dir den aktuellen Code mal an: [ArticleModel_C35.php#L185](https://github.com/fritzmg/contao-inherit-article/blob/1.2.0/system/modules/inherit_article/models/ArticleModel_C35.php#L185). Benutzerfreundlich sollte das Ganze natürlich auch bleiben.

**Comment by pet21221** [comment]
Verstehe; ich habe es mal auf die schnelle angesehen. Die entsprechende Sortierung kann doch dann auch in PHP erfolgen. Ab Zeile 254 sollte die Sortierung in PHP gemacht werden, so wie ich es jetzt auf Anhieb gesehen habe. Mit $arrModels habe ich ja alle Artikel in dieser Spalte. Wenn ich in der Datenbank noch ein Wert dafür gespeichert habe, gehe ich mit PHP hin und sortiere alles nach diesem Wert?

**Comment by fritzmg** [comment]
> Mit $arrModels habe ich ja alle Artikel in dieser Spalte. Wenn ich in der Datenbank noch ein Wert dafür gespeichert habe, gehe ich mit PHP hin und sortiere alles nach diesem Wert?

`$arrModels` sind nur die Artikel einer Spalte für eine Page. Nach dem zusätzlichen Sortierungswert sortieren bringt dort nichts, weil du willst ja, dass die vererbten Artikel aus den Parent Pages ggf. davor oder dahinter sein sollen.

Hm, man könnte vielleicht die aktuelle Sortierung komplett entfernen und am Schluss einfach nochmal nach `priority` und dann nach `sorting` sortieren lassen. Nur gefällt mir das nicht, weil man dann zB eine default priority definieren muss - zB `0` - und wenn ein vererbter Artikel hinter den anderen sein soll, muss man `-1` eingeben. Wenn er davor sein soll `1`, wenn er vor einem nicht vererbten Artikel sein solla ber hinter einem anderen Artikel muss man `1` respektive `2` einstellen, etc.

**Comment by pet21221** [comment]
Okay, dass ganze wird doch etwas herausfordernder. Gerade für mich, der noch nie mit Contao gearbeitet hat. Für mich war es eine Typo3 Vereinfachung. Wenn ich die Zeit finden sollte demnächst, werde ich mir mal die Contao „Erweiterungen“ etc. anschauen, um mehr Verständnis vom ganzen zu bekommen. Ansonsten schaue ich mir auch mal boxes4ward an. 

Trotzdem danke; für das was du bereits zur Verfügung gestellt hast. 

Gruß

**Comment by fritzmg** [comment]
Wie gesagt, das ist ja kein Contao spezifisches Problem.

**Comment by fritzmg** [comment]
In Version `1.3.0` kann man nun eine Priorität angeben.

**Comment by pet21221** [comment]
Hi fritzmg,

ich nutze inherit_article 1.3.3 mit Contao 3.5.25. Mir ist aufgefallen, dass die Prio nicht so ganz funktioniert. Oder ich habe es noch nicht so ganz verstanden, bzgl. der negativen Werte.

Sagen wir, ich habe folgende Seiten:
1. Pages (/pages/)
1.1 Kontakt (/pages/contact/)

Unter Pages habe ich ein Artikel, welches vererbt wird. Prio habe ich auf 1 gesetzt.
Dann gibt es die darunter existierende Seite Kontakt. Dort habe ich ebenfalls einen Artikel, wo ich die Prio auf 0 gesetzt habe (Soll vor dem vererbten Artikel platziert werden) und einen weiteren Artikel, welches hinter dem verebten Artikel (Prio 3) platziert werden soll. So ganz funktioniert das allerdings nicht. Der vererbte Artikel erscheint bei mir immer ganz oben, es sei dem ich gib ihm ein negativ Wert. Dann wiederum ist ganz unten.

Kurz gefasst:
Pages hat einen Artikel mit Prio 2
Kontakt hat zwei Artikel mit Prio 1 und Prio 3.
Der vererbte Artikel von Pages soll also unter Kontakt zwischen den zwei Artikeln erscheinen.

--

Macht es eventuell auch nicht Sinn, auch den nicht vererbten Artikeln die Möglichkeit zur Prio zu geben? So könnte ich auf das Vereben unter Kontakt verzichten, um nur die Prio zu definieren. Die müssten nämlich nicht vererbt werden müssen, sondern nur richtig priorisiert werden. Oder macht es das ganze komplexer?

Vielen Dank.

**Comment by fritzmg** [comment]
Derzeit ist es tatsächlich so (wenn ich mich richtig erinnere), dass vererbte Artikel grundsätzlich nur vor oder nach nicht vererbten Artikel angezeigt werden können.

Wenn ich Zeit habe sehe ich mir das mal an.

**Comment by pet21221** [comment]
Ich habe die auf der Unterseite befindenden Artikel ebenfalls auch als "Vererbbar" gemacht, gerade damit ich priorisieren kann. Auch das hat hierbei nicht geholfen.

Das wäre super. Vielen Dank.

**Comment by pet21221** [comment]
Hi fritzmg, gibt es schon neues zum Thema? Zudem habe ich soeben bei mir Contao 4.4 installiert und wollte auf das Plugin zurückgreifen, da ich sehr zufrieden mit damit. Allerdings ist es scheinbar nicht kompatibel. Ist in der Richtung etwas geplant?

**Comment by fritzmg** [comment]
Nein, so wie die Extension programmiert ist, kann sie in Contao 4 nicht eingesetzt werden.

Es gibt nun allerdings https://github.com/contao-community-alliance/merger2 - habe es mir aber noch nicht selbst angesehen.

**Comment by pet21221** [comment]
Schade, aber ich schaue mir mal merger2 an. Vielen Dank!

**Comment by fritzmg** [comment]
Ich habe nun nichts desto trotz doch einen release für Contao 4 gemacht. Dort sollte auch die unabhängige Sortierung anhand der Priorität funktionieren :)
