### ISSUE TITLE
Prio fehlerhaft

### ISSUE THREAD

**Issue by ngdot** [fritzmg/contao-inherit-article#4]
Hi, leider funktioniert die Option "Priorität" nicht korrekt.
Ich hätte gerne das mein Artikel (Einer von 5, an Position 2) an die untergeordneten Seiten vererbt wird, und zwar immer als letzter Stelle. Dies ging mit der alten Version problemlos ("An letzte Stelle einfügen"). Egal welchen Wert ich nun unter "Priorität" eingebe, der Artikel verändert auf der Original Seite seine Position, was natürlich total falsch ist! Die Position auf den vererbten Seiten ist allerdings korrekt.

**Comment by fritzmg** [comment]
Hm, die Darstellung auf der Original Seite sollte eigentlich unangetastet sein. Ich werde das nochmal prüfen.

**Comment by ngdot** [comment]
Habe es mit mehrere Installationen ausprobiert, irgendwas läuft da falsch.. Er packt mir den Original Artikel den ich vererben möchte, immer auf Position 1 obwohl er z.B. eig. an dritter Stelle steht. Auf der Verberungs-Seite ist er aber wie gesagt korrekt nach der zugewiesenen Priorität zugeordnet. Kann leider nicht nachvollziehen warum :/

**Comment by fritzmg** [comment]
Habe es gerade getestet und kann das Problem auf jeden Fall nachvollziehen.

**Comment by fritzmg** [comment]
fixed in e4830e5

**Comment by ngdot** [comment]
Läuft 1a :) Danke dir!
