### ISSUE TITLE
Contao 4

### ISSUE THREAD

**Issue by ngdot** [fritzmg/contao-inherit-article#6]
Sobald die Erweiterung unter Contao 4.3.10 installiert wird, ist es nicht mehr möglich Seiten zu speichern. Folgender Fehler erscheint:

Fatal Error
Unknown method findPublishedWithTeaserByPid

Würde Sie super gerne unter Contao 4 verwenden, gibt es schön Pläne dazu?
VG Nicolas

**Comment by fritzmg** [comment]
Probier mal `dev-master` :)

**Comment by ngdot** [comment]
Schnellster Bugfix ever! Funktioniert, kannst raushauen. 👍

**Comment by fritzmg** [comment]
`1.3.4` released
