### ISSUE TITLE
Exclude from parent page

### ISSUE THREAD

**Issue by Aybee** [fritzmg/contao-inherit-article#7]
Hallo Fritz, wäre es möglich noch eine Option hinzuzufügen, dass ein Artikel auf der Seite selber **nicht** angezeigt wird, sondern **nur** auf den Unterseiten?

EN:
Hi Fritz, would it be possible to add an option that an article on the page itself ** not ** is displayed, but ** only ** on the child pages?

**Comment by fritzmg** [comment]
🤔  hmm - I'd rather use it the other way around: having an option to let it show in the child pages, even if the article itself is not published. Otherwise I'd have to circumvent Contao's own visibility check for the regular article. But I'll consider it.

**Comment by Aybee** [comment]
Ah, if I can inherit from a parent page, set the parent article to unvisible and there is an option to show it on child pages also the parent article is invisible, that will help me. So I think this ticket can be closed.

**Comment by fritzmg** [comment]
Oh, if this already works, then it's a bug 😁

I would expect the article to not be visible anywhere, if it is invisible (neither its own page nor the child pages).

**Comment by Aybee** [comment]
Mal auf Deutsch: Das hätte ich auch erwartet, aber du sagst doch
> having an option to let it show in the child pages, even if the article itself is not published

Das habe ich so verstanden, dass dies schon funktioniert. Habe ich das falsch verstanden?

**Comment by fritzmg** [comment]
Ja - also das (sollte) noch nicht funktionieren. Das müsste ich erst einbauen.

**Comment by fritzmg** [comment]
Released in `2.1.0` :)

**Comment by Aybee** [comment]
Thank you so much. I will test it at the next opportunity.
